# Generated by Django 4.0.6 on 2022-07-20 14:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('core_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('create_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email_address')),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('job_assigned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('has_restaurant', models.BooleanField(default=False)),
                ('car_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('car_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=255, null=True), blank=True, default=list, null=True, size=None)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
