# Generated by Django 4.0.6 on 2022-07-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
