# Generated by Django 4.0.6 on 2022-07-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_core_id_coreuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='is_stuff',
            field=models.BooleanField(default=True),
        ),
    ]
