# Generated by Django 4.0.6 on 2022-07-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coreuser_is_stuff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreuser',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
