# Generated by Django 4.0.6 on 2022-07-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_is_stuff_coreuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
